import Image from "next/image";
import {
  FaStar,
  FaStarHalfAlt,
  FaShoppingCart,
  FaQuestionCircle,
  FaCheckCircle,
  FaBoxOpen,
} from "react-icons/fa";
import { MdDiscount } from "react-icons/md";
import { getSingleProduct } from "@/actions/Server/Product";


export const metadata = {
  title: "Product Details",
  description: "Generated by create Hero Kidz",
};

const ProductDetails = async ({ params }) => {
  const { productId } = await params;
  const product = await getSingleProduct(productId);

  const discountedPrice =
    product.price - (product.price * product.discount) / 100;

  return (
    <section className="max-w-7xl mx-auto px-5 py-10">
      {/* Top Section */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-12">
        {/* Image */}
        <div className="h-120 w-120 bg-base-200 rounded-xl p-6">
          <Image
            src={product.image}
            alt={product.bangla}
            width={450}
            height={450}
            className="rounded-xl object-contain"
          />
        </div>

        {/* Info */}
        <div>
          <h1 className="text-3xl font-bold">{product.bangla}</h1>
          <p className="text-gray-500 mt-1">{product.title}</p>

          {/* Rating */}
          <div className="flex items-center gap-2 mt-3 text-warning">
            <FaStar />
            <FaStar />
            <FaStar />
            <FaStar />
            <FaStarHalfAlt />
            <span className="text-gray-600 ml-2">
              {product.ratings} রেটিং | {product.reviews} রিভিউ | {product.sold}{" "}
              বিক্রি
            </span>
          </div>

          {/* Price */}
          <div className="mt-5 flex items-center gap-4">
            <span className="text-4xl font-bold text-primary">
              ৳{discountedPrice}
            </span>
            <span className="line-through text-gray-400">৳{product.price}</span>
            <span className="badge badge-error flex items-center gap-1">
              <MdDiscount /> {product.discount}% ছাড়
            </span>
          </div>

          {/* Description */}
          <p className="mt-6 text-gray-700 leading-relaxed whitespace-pre-line">
            {product.description}
          </p>

          {/* Features */}
          <div className="mt-6">
            <h3 className="font-semibold text-lg flex items-center gap-2">
              <FaBoxOpen /> পণ্যের বৈশিষ্ট্য
            </h3>
            <ul className="mt-3 space-y-2">
              {product.info.map((item, index) => (
                <li
                  key={index}
                  className="flex items-center gap-2 text-gray-700"
                >
                  <FaCheckCircle className="text-success" /> {item}
                </li>
              ))}
            </ul>
          </div>

          {/* Buttons */}
          <div className="mt-8 flex gap-4">
            <button className="btn btn-primary flex items-center gap-2">
              <FaShoppingCart /> Add to cart
            </button>
            <button className="btn btn-outline btn-secondary">
              Buy now
            </button>
          </div>
        </div>
      </div>

      {/* Q&A Section */}
      <div className="mt-16">
        <h2 className="text-2xl font-bold flex items-center gap-2">
          <FaQuestionCircle /> প্রশ্ন ও উত্তর
        </h2>

        <div className="mt-6 space-y-4">
          {product.qna.map((item, index) => (
            <div
              key={index}
              className="p-4 border rounded-lg bg-base-100 shadow-sm"
            >
              <p className="font-semibold">❓ {item.question}</p>
              <p className="mt-2 text-gray-600">✔ {item.answer}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default ProductDetails;
