import { Poppins } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar";
import Footer from "@/components/layouts/Footer";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const fontBangla = localFont({
  src: "../fonts/mayaboti-normal.ttf",
});

export const metadata = {
  title: {
    default: "Hero Kidz | Home",
    template: "%s | Hero Kidz",
  },
  description: "Generated by create Hero Kidz",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased min-h-screen flex flex-col`}
      >
        <header className="bg-white sticky top-0 z-50 shadow-md">
          <Navbar></Navbar>
        </header>
        {children}
        <footer>
          <Footer></Footer>
        </footer>
      </body>
    </html>
  );
}
